apiVersion: v1
kind: Namespace
metadata:
  name: fightclub
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fightclub-dpl
  namespace: fightclub
  labels:
    app: website
    role: frontpage
    tier: frontend
    version: v1
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 6
  paused: false  
  minReadySeconds: 10
  selector:
    matchLabels: 
      app: website
      role: frontpage
      tier: frontend
  template:
    metadata:
      name: fightclub-pod
      labels:
        app: website
        role: frontpage
        tier: frontend
    spec:
      containers:
        - name: demo-container
          image: gcr.io/$PROJECT_ID/fightclub:latest
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fightclub-srv
  namespace: fightclub
  labels:
    app: website
    role: frontpage
    tier: frontend
    version: v1
spec:
  type: LoadBalancer
  loadBalancerIP: ""
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: website
    role: frontpage
    tier: frontend
